goLint: add a check that go.mod is tidied

diff --git a/.github/workflows/goLint.yml b/.github/workflows/goLint.yml
--- a/.github/workflows/goLint.yml
+++ b/.github/workflows/goLint.yml
@@ -66,8 +66,16 @@ jobs:
         run: |
           git config --global url.https://${{ secrets.PAT }}@github.com/.insteadOf git+ssh://git@github.com
           git config --global url.git@github.com:.insteadOf https://github.com/
+      - name: Check that go.mod is tidied
+        run: |
+          cp go.mod go.mod.orig
+          cp go.sum go.sum.orig
+          go mod tidy
+          diff go.mod go.mod.orig
+          diff go.sum go.sum.orig
       - name: Run Linter
         uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6.5.2
+        if: success() || failure() # run this step even if the previous one failed
         with:
           version: ${{ inputs.golangci-lint-version }}
           args: '${{ inputs.golangci-lint-args }}'
